import type { Metadata } from "next";
import {} from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Header } from "@/components/header";
import { GeistMono } from "geist/font/mono";
import { ThemeProvider } from "@/components/theme-provider";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Image Gallery App",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistMono.variable}>
        <Providers>
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex flex-col flex-1 dark:bg-background">
              {children}
            </main>
          </div>
        </Providers>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
