// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type DeletePictureResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Image struct {
    ID       string `json:"id" bson:"_id,omitempty"`
	URL      string `json:"url"`
	Filename string `json:"filename"`
	UserID   string `json:"userId"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
    ID       string `json:"id" bson:"_id,omitempty"`
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
